FROM ghcr.io/tiiuae/fog-ros-baseimage-builder:sha-839ea56 AS builder

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        angles-dev \
    && rm -rf /var/lib/apt/lists/*

COPY . $SRC_DIR/mocap_pose

RUN /packaging/build_colcon.sh

#  ▲               runtime ──┐
#  └── build                 ▼

FROM ghcr.io/tiiuae/fog-ros-baseimage:sha-839ea56

ENTRYPOINT [ "/entrypoint.sh" ]

COPY entrypoint.sh /entrypoint.sh

COPY --from=builder $INSTALL_DIR  $INSTALL_DIR
