# Use one base image for all the components.
# First tests can be done using debian packages of release 6.0.1.
FROM tii-fog-ros-base-image:devel

RUN apt install -y \
	ros-${ROS_DISTRO}-mocap-pose=0.1.1-47~git20220120.d624ade

COPY entrypoint_runtime.sh .
RUN chmod +x entrypoint_runtime.sh

USER runner

ENTRYPOINT "/entrypoint_runtime.sh"
