name: main

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  tii-deb-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout mocap_pose
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Build .deb
        run: |
          set -eux
          mkdir bin
          cd fogsw-ci-scripts/
          ./generate_deb.sh .. ../bin/

          # generate_deb.sh replaces Dockerfile from our repo with its own so we got to go and repair
          # it because otherwise the following Docker build would use the incorrect Dockerfile
          cd ..
          git checkout HEAD -- Dockerfile
