name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tii-deb-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout mocap_pose
        uses: actions/checkout@v2
        with:
          path: mocap_pose
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      # Run docker build
      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../mocap_pose ../bin/
          popd
