name: tii-octomap-server2-coverity

on:
  repository_dispatch:
  push:
    branches:
      - main

jobs:
  coverity:
    runs-on: octomap-server2-self-hosted-coverity
    steps:
      - uses: actions/checkout@
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build coverity scan image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: coverity-scan-image-self-hosted:latest
          file: Dockerfile.coverity
      - name: Run coverity scan
        run:
          docker run coverity-scan-image-self-hosted:latest
